
Biker.create(first_name: "Dustin", last_name: "Green", city_of_origin: "Hickory Hills", state_of_origin: "IL")
Biker.create(first_name: "Jason", last_name: "Finn", city_of_origin: "Huntington Beach", state_of_origin: "CA")
Biker.create(first_name: "Howard", last_name: "Thompson", city_of_origin: "Hale", state_of_origin: "MO")
Biker.create(first_name: "Maggie", last_name: "Lantz", city_of_origin: "Dublin", state_of_origin: "OH")
Biker.create(first_name: "Lawrence", last_name: "Duran", city_of_origin: "Fort Myers", state_of_origin: "FL")
Biker.create(first_name: "Irene", last_name: "Molina", city_of_origin: "Tucson", state_of_origin: "AZ")
Biker.create(first_name: "Nancy", last_name: "Garner", city_of_origin: "Baltimore", state_of_origin: "MD")
Biker.create(first_name: "Tara", last_name: "Taylor", city_of_origin: "Minneapolis", state_of_origin: "MN")
Biker.create(first_name: "Alejandro", last_name: "Smith", city_of_origin: "Scarborough", state_of_origin: "ME")
Biker.create(first_name: "Tricia", last_name: "Renshaw", city_of_origin: "Mystic", state_of_origin: "CT")
Biker.create(first_name: "Travis", last_name: "Cook", city_of_origin: "Twin Lakes", state_of_origin: "WI")
Biker.create(first_name: "Joan", last_name: "Brooks", city_of_origin: "Norfolk", state_of_origin: "VA")
Biker.create(first_name: "Joseph", last_name: "Rodgers", city_of_origin: "Wayne", state_of_origin: "NJ")
Biker.create(first_name: "Matthew", last_name: "Gregson", city_of_origin: "Brashear", state_of_origin: "MO")
Biker.create(first_name: "Katie", last_name: "Dunlap", city_of_origin: "Marion", state_of_origin: "VA")
Biker.create(first_name: "Leo", last_name: "Howard", city_of_origin: "Dallas", state_of_origin: "TX")
Biker.create(first_name: "Maria", last_name: "Baisden", city_of_origin: "Raleigh", state_of_origin: "NC")
Biker.create(first_name: "Sandy", last_name: "Townsend", city_of_origin: "Newport", state_of_origin: "PA")
Biker.create(first_name: "Melinda", last_name: "Stephenson", city_of_origin: "Kahului", state_of_origin: "HI")
Biker.create(first_name: "Jason", last_name: "Nichols", city_of_origin: "Alexandria", state_of_origin: "VA")

